export class PHPGenerator {
  static generateThemeHeader(options: {
    themeName: string;
    themeAuthor?: string;
    themeDescription?: string;
    themeVersion?: string;
  }): string {
    return `/*
Theme Name: ${options.themeName}
Theme URI: https://example.com/
Author: ${options.themeAuthor || 'Website Cloner Pro'}
Author URI: https://example.com/
Description: ${options.themeDescription || 'A 100% plugin-free theme generated from cloned website'}
Version: ${options.themeVersion || '1.0.0'}
License: GNU General Public License v2 or later
License URI: http://www.gnu.org/licenses/gpl-2.0.html
Text Domain: custom-cloned-theme
Tags: custom, cloned, plugin-free, performance

This theme requires ZERO plugins - all functionality is native WordPress.
*/`;
  }

  static generateFunctionsPhp(cssFiles: number, jsFiles: number, version: string): string {
    return `<?php
/**
 * Theme Functions
 * Generated by Website Cloner Pro
 * ✅ 100% Plugin-Free
 */

if (!defined('ABSPATH')) exit;

function custom_cloned_theme_enqueue_assets() {
    wp_enqueue_style('custom-cloned-theme-style', get_stylesheet_uri(), array(), '${version}');

${Array.from({ length: cssFiles }, (_, i) => `    wp_enqueue_style('custom-css-${i}', get_template_directory_uri() . '/assets/css/custom-${i}.css', array(), '${version}');`).join('\n')}

${Array.from({ length: jsFiles }, (_, i) => `    wp_enqueue_script('custom-js-${i}', get_template_directory_uri() . '/assets/js/custom-${i}.js', array('jquery'), '${version}', true);`).join('\n')}
}
add_action('wp_enqueue_scripts', 'custom_cloned_theme_enqueue_assets');

function custom_cloned_theme_setup() {
    add_theme_support('title-tag');
    add_theme_support('post-thumbnails');
    add_theme_support('html5', array('search-form', 'comment-form', 'comment-list', 'gallery', 'caption'));
    add_theme_support('custom-logo');
    add_theme_support('responsive-embeds');

    register_nav_menus(array(
        'primary' => __('Primary Menu', 'custom-cloned-theme'),
        'footer' => __('Footer Menu', 'custom-cloned-theme'),
    ));
}
add_action('after_setup_theme', 'custom_cloned_theme_setup');

function custom_cloned_theme_widgets_init() {
    register_sidebar(array(
        'name' => __('Sidebar', 'custom-cloned-theme'),
        'id' => 'sidebar-1',
        'before_widget' => '<section id="%1$s" class="widget %2$s">',
        'after_widget' => '</section>',
        'before_title' => '<h2 class="widget-title">',
        'after_title' => '</h2>',
    ));
}
add_action('widgets_init', 'custom_cloned_theme_widgets_init');
?>`;
  }

  static generateIndexPhp(bodyContent: string): string {
    return `<?php
/**
 * Main Template File
 */
get_header();
?>

<main id="main-content" class="site-main" role="main">
    <?php
    if (have_posts()) :
        while (have_posts()) : the_post();
            the_content();
        endwhile;
    else :
        ?>
        ${bodyContent}
        <?php
    endif;
    ?>
</main>

<?php get_footer(); ?>`;
  }

  static generateHeaderPhp(headContent: string): string {
    return `<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
    <meta charset="<?php bloginfo('charset'); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    ${headContent}
    <?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>
<?php wp_body_open(); ?>
<div id="page" class="site">
    <header id="masthead" class="site-header">
        <div class="site-branding">
            <?php
            if (has_custom_logo()) :
                the_custom_logo();
            else :
                ?>
                <h1 class="site-title">
                    <a href="<?php echo esc_url(home_url('/')); ?>"><?php bloginfo('name'); ?></a>
                </h1>
                <?php
            endif;
            ?>
        </div>
        <nav id="site-navigation">
            <?php wp_nav_menu(array('theme_location' => 'primary', 'menu_id' => 'primary-menu')); ?>
        </nav>
    </header>
    <div id="content" class="site-content">`;
  }

  static generateFooterPhp(): string {
    return `    </div>
    <footer id="colophon" class="site-footer">
        <div class="site-info">
            <p>&copy; <?php echo date('Y'); ?> <?php bloginfo('name'); ?>. All rights reserved.</p>
        </div>
        <nav id="footer-navigation">
            <?php wp_nav_menu(array('theme_location' => 'footer', 'menu_id' => 'footer-menu')); ?>
        </nav>
    </footer>
</div>
<?php wp_footer(); ?>
</body>
</html>`;
  }
}
