import * as cheerio from 'cheerio';
import type JSZip from 'jszip';
import type { WordPressExportOptions } from '../../../types/wordpress-export.types';

/**
 * Bricks Builder - Modern WordPress page builder
 */
export class BricksBuilder {
  async generate(zip: JSZip, options: WordPressExportOptions, files: any): Promise<void> {
    const folder = zip.folder('bricks-layout')!;
    const bricksData = this.convertToBricks(options.html);

    folder.file('bricks-template.json', JSON.stringify(bricksData, null, 2));
    files.templates = files.templates || [];
    files.templates.push('bricks-template.json');

    folder.file('README.md', `# Bricks Builder Template\n\nImport via Bricks > Templates > Import.\n\n**Generated by Website Cloner Pro**`);
  }

  private convertToBricks(html: string): any {
    const $ = cheerio.load(html);
    const elements: any[] = [];

    $('body').children().each((_, el) => {
      const $el = $(el);
      const tag = $el.prop('tagName')?.toLowerCase();

      if (['script', 'style', 'noscript'].includes(tag)) return;

      elements.push({
        id: this.generateId(),
        name: tag === 'section' ? 'section' : 'block',
        parent: 0,
        children: [],
        settings: {
          _tag: tag,
          _content: $el.html() || '',
        },
      });
    });

    return { content_type: 'template', content: elements, version: '1.0' };
  }

  private generateId(): string {
    return Math.random().toString(36).substr(2, 9);
  }
}
