import * as cheerio from 'cheerio';
import type JSZip from 'jszip';
import type { WordPressExportOptions } from '../../../types/wordpress-export.types';

/**
 * Brizy Builder - Visual page builder
 */
export class BrizyBuilder {
  async generate(zip: JSZip, options: WordPressExportOptions, files: any): Promise<void> {
    const folder = zip.folder('brizy-layout')!;
    const brizyData = this.convertToBrizy(options.html);

    folder.file('brizy-template.json', JSON.stringify(brizyData, null, 2));
    files.templates = files.templates || [];
    files.templates.push('brizy-template.json');

    folder.file('README.md', `# Brizy Template\n\nImport via Brizy > Saved Blocks > Import.\n\n**Generated by Website Cloner Pro**`);
  }

  private convertToBrizy(html: string): any {
    const $ = cheerio.load(html);
    const items: any[] = [];

    $('body').children().each((_, el) => {
      const $el = $(el);
      const tag = $el.prop('tagName')?.toLowerCase();

      if (['script', 'style', 'noscript'].includes(tag)) return;

      items.push({
        type: 'Section',
        value: {
          _styles: ['section'],
          items: [{
            type: 'SectionItem',
            value: {
              items: [{
                type: 'Wrapper',
                value: {
                  items: [{
                    type: 'RichText',
                    value: {
                      text: $el.html() || '',
                    },
                  }],
                },
              }],
            },
          }],
        },
      });
    });

    return { version: 2, items };
  }
}
