import * as cheerio from 'cheerio';
import type JSZip from 'jszip';
import type { WordPressExportOptions } from '../../../types/wordpress-export.types';

/**
 * Kadence Blocks - Gutenberg-based builder
 */
export class KadenceBuilder {
  async generate(zip: JSZip, options: WordPressExportOptions, files: any): Promise<void> {
    const folder = zip.folder('kadence-blocks')!;
    const blocksHTML = this.convertToKadence(options.html);

    folder.file('kadence-blocks.html', blocksHTML);
    files.templates = files.templates || [];
    files.templates.push('kadence-blocks.html');

    folder.file('README.md', `# Kadence Blocks\n\nPaste into WordPress Code Editor.\n\n**Generated by Website Cloner Pro**`);
  }

  private convertToKadence(html: string): string {
    const $ = cheerio.load(html);
    const blocks: string[] = [];

    $('body').children().each((_, el) => {
      const $el = $(el);
      const tag = $el.prop('tagName')?.toLowerCase();

      if (['script', 'style', 'noscript'].includes(tag)) return;

      if (['h1', 'h2', 'h3', 'h4', 'h5', 'h6'].includes(tag)) {
        blocks.push(`<!-- wp:kadence/advancedheading {"content":"${this.escape($el.html())}"} /-->`);
      } else if (tag === 'p') {
        blocks.push(`<!-- wp:paragraph -->\n<p>${$el.html()}</p>\n<!-- /wp:paragraph -->`);
      } else {
        blocks.push(`<!-- wp:html -->\n${$.html($el)}\n<!-- /wp:html -->`);
      }
    });

    return blocks.join('\n\n');
  }

  private escape(text: string): string {
    return (text || '').replace(/"/g, '\\"').replace(/\n/g, ' ');
  }
}
