import * as cheerio from 'cheerio';
import type JSZip from 'jszip';
import type { WordPressExportOptions } from '../../../types/wordpress-export.types';

/**
 * OptimizePress - Landing page and funnel builder
 */
export class OptimizePressBuilder {
  async generate(zip: JSZip, options: WordPressExportOptions, files: any): Promise<void> {
    const folder = zip.folder('optimizepress-layout')!;
    const opData = this.convertToOptimizePress(options.html);

    folder.file('op-template.json', JSON.stringify(opData, null, 2));
    files.templates = files.templates || [];
    files.templates.push('op-template.json');

    folder.file('README.md', `# OptimizePress Template\n\nImport via OptimizePress > Templates > Import.\n\n**Generated by Website Cloner Pro**`);
  }

  private convertToOptimizePress(html: string): any {
    const $ = cheerio.load(html);
    const sections: any[] = [];

    $('body').children().each((_, el) => {
      const $el = $(el);
      const tag = $el.prop('tagName')?.toLowerCase();

      if (['script', 'style', 'noscript'].includes(tag)) return;

      sections.push({
        id: this.generateId(),
        type: 'section',
        data: {
          html: $.html($el) || '',
          settings: {
            background: 'none',
            padding: { top: 20, bottom: 20 },
          },
        },
      });
    });

    return { version: '3.0', type: 'page', sections };
  }

  private generateId(): string {
    return `op_${Date.now()}_${Math.random().toString(36).substr(2, 6)}`;
  }
}
