import * as cheerio from 'cheerio';
import type JSZip from 'jszip';
import type { WordPressExportOptions } from '../../../types/wordpress-export.types';

/**
 * Oxygen Builder - Visual website builder
 */
export class OxygenBuilder {
  async generate(zip: JSZip, options: WordPressExportOptions, files: any): Promise<void> {
    const folder = zip.folder('oxygen-layout')!;
    const oxygenData = this.convertToOxygen(options.html);

    folder.file('oxygen-template.json', JSON.stringify(oxygenData, null, 2));
    files.templates = files.templates || [];
    files.templates.push('oxygen-template.json');

    folder.file('README.md', `# Oxygen Builder Template\n\nImport via Oxygen > Templates > Import.\n\n**Generated by Website Cloner Pro**`);
  }

  private convertToOxygen(html: string): any {
    const $ = cheerio.load(html);
    const components: any[] = [];

    $('body').children().each((_, el) => {
      const $el = $(el);
      const tag = $el.prop('tagName')?.toLowerCase();

      if (['script', 'style', 'noscript'].includes(tag)) return;

      components.push({
        id: this.generateId(),
        name: 'ct_div_block',
        options: {
          ct_content: $el.html() || '',
          ct_id: this.generateId(),
        },
        children: [],
      });
    });

    return { template_type: 'oxygen_template', ct_builder_shortcodes: components };
  }

  private generateId(): number {
    return Math.floor(Math.random() * 1000000);
  }
}
